version: '3.8'

services:

  # Service FastAPI — Livres
  service-livres:
    build: .
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://admin:secret@db-livres:5432/livres_db
    depends_on:
      - db-livres
    networks:
      - livres-network

  # Base de données PostgreSQL
  db-livres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: livres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - livres-network

  # Frontend nginx
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - service-livres
    networks:
      - livres-network

networks:
  livres-network:
    driver: bridge

volumes:
  pgdata: